exports.lookup = {
    'Running a Node App': 1,
    "The Rise Of Thinking Machines: How IBM's Watson Takes On The World": 2,
    '22 Amazing open source React projects': 3,
    'Making sense of Redux': 4,
    'Please stop worrying about Angular 3': 5,
    'JavaScript’s Apply, Call, and Bind Methods are Essential for JavaScript Professionals': 6,
    'Using React Native: One Year Later': 7,
    'Express.js: A Server-Side JavaScript Framework': 8,
    'Learn HTML5, CSS3, and Responsive WebSite Design in One Go': 9,
    'An Introduction to JavaScript Object Notation (JSON) in JavaScript and .NET': 10,
    'Designing Better JavaScript APIs': 11,
    'The battle for Node.js security has only begun': 12,
    "What does Jose Mourinho's handwriting say about his personality?": 13,
    'Who Will Manage Your Club in 2021?': 14,
    'Why do England managers keep making the same mistakes?': 15,
    'History of FC Barcelona': 16,
    'Which current Premier League manager was the best player?': 17,
    'The People Tracking Every Touch, Pass And Tackle in the World Cup': 18,
    'Who are the most followed clubs and players on Instagram?': 19,
    'History of Football': 20,
    'Agility Training Drills For Football Players': 21,
    'Defensive Metrics: Measuring the Intensity of a High Press': 22,
    'Sunday league football': 23,
    'Game of talents: management lessons from top football coaches': 24,
    'Sweet potato & butternut squash soup with lemon & garlic toast': 25,
    'HOW COOKING HAS CHANGED US': 26,
    'Thanksgiving Drinks for Everyone': 27,
    'High Altitude Cooking': 28,
    'A BRIEF HISTORY OF FOOD—NO BIG DEAL': 29,
    'Twice-Baked Butternut Squash Is the Thanksgiving Side Dish of Your Dreams': 30,
    'What to Cook This Week': 31,
    'Halal food: Keeping pure and true': 32,
    'Seafood substitutions are increasing': 33,
    'The Notorious MSG’s Unlikely Formula For Success': 34,
    'Stone Soup': 35,
    'The vegan carnivore?': 36
};